
#Run this file through homebrew bundle

#Tap section
tap 'homebrew/bundle'
tap 'puma/puma'

#Brew section
brew 'git'			# Newest version of Github CLI
#brew 'rbenv' 			# Lightweight Ruby environment manager
#brew 'ruby-build'		# Control ruby versions
#brew 'python3' 			# Newest version of Python 3
#brew 'node --without-npm'	# Node.js without the NPM package manager. Consider installing NPM manually on the side, or use Yarn
#brew 'vim'			# Editor -- consider adding options to control linking to Python 3 vs 2
#brew 'tmux' 			# TMUX terminal multiplexer
brew 'zsh'			# Zshell
brew 'zsh-completions'		# Tab-completions for Zshell
#brew 'mas'			# Mac App Store CLI
#brew 'heroku-toolbelt' 		#Heroku deployment CLI for Rails apps
#brew 'boost' 			# C++ boost libraries
#brew 'mc' 			# Midnight commander - just like Norton Commander

#Cask section
#cask 'iterm2'			# iTerm2 - an improvement on Terminal
#cask 'dashlane'			# Password manager
#cask 'google-chrome'	
#cask 'garmin-express'
#cask 'spotify'
#cask 'evernote'
#cask 'skype'
